@host = https://localhost:7013
@jobId = d1fc0735-64d6-4bdc-a857-1a45bcb7e222

#Request an archive job
POST {{host}}/api/archive/start
Content-Type: application/json
{
  "StartDate": "2019-06-01",
  "EndDate": "2024-01-01"
}

### Request an archive job status
GET {{host}}/api/archive/status/{{jobId}}

### Download an archive
GET {{host}}/api/archive/download/{{jobId}}
