@host = https://localhost:7013
@jobId = 25f9228f-605f-44fd-9b9a-c4f9980e3a8c
@imageId = 1

#Request an archive job
POST {{host}}/api/archive/start
Content-Type: application/json
{
  "StartDate": "2019-06-01",
  "EndDate": "2024-01-01"
}

### Request an archive job status
GET {{host}}/api/archive/status/{{jobId}}

### Download an archive
GET {{host}}/api/archive/download/{{jobId}}

###
GET {{host}}/api/images/paginated?startDate=2010-01-01&endDate=2023-12-31&pageIndex=1&pageSize=8

###
GET {{host}}/api/images/{{imageId}}